### ISSUE TITLE
IPAD : Background Refresh

### ISSUE THREAD

**Issue by SathiWork** [Sriram-Ananth/EDGEPACS#21]
Device: 2nd Generation IPAD
Browser: Chrome

There seems to be a problem in Background refresh, when I tab/switch between applications. Please see attached screen shot.

![image](https://user-images.githubusercontent.com/62637807/77882468-a0f3cf00-727e-11ea-9b9b-1b7d76cff5df.png)

**Comment by Sriram-Ananth** [comment]
Think this issue has been fixed. Sathi can you confirm please? Reopen this if you still find the issue.

**Comment by SathiWork** [comment]
No @Sriram-Ananth. Unfortunately, the issue persists. I am attaching two pictures. 
a) Before switching to another app
b) Back after switching to another app
![E71D22C4-ACFD-417B-89A2-06ED30E7E17D](https://user-images.githubusercontent.com/62637807/78357515-3a98e480-75cf-11ea-94f4-3a8f9ef71149.png)
![58A0FA06-B17C-44C7-B62A-0FA6ED6983C4](https://user-images.githubusercontent.com/62637807/78357532-41bff280-75cf-11ea-82c7-97a8c68e55fd.png)

**Comment by SathiWork** [comment]
@Sriram-Ananth , this problem is still persisting.
￼￼
![image](https://user-images.githubusercontent.com/62637807/78552107-8395a680-7824-11ea-91a5-5035faf0b6df.png)

**Comment by Sriram-Ananth** [comment]
Yes. This is also a bug in the component set. I wrote to them and they confirmed the issue. They said he will provide a fix in the next release which should be later this week.

**Comment by SathiWork** [comment]
Surprisingly, this works on all browsers in Windows PC mode but fails to work in tablet mode

**Comment by Sriram-Ananth** [comment]
Fixed. Please check and confirm
